version: "3"

services:
  app:
      image: "node:18.16.0"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      env_file:
      - .env
      volumes:
        - ./:/home/node/app
      ports:
        - "7777:7777"
      expose:
        - "7777"
      command: "npm start"

  db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - conectDB
    env_file:
      - .env
networks:
  conectDB:
    driver: bridge

volumes:
  mongodb_data:
