version: "3"

services:
  app:
      build: .
      environment:
        - NODE_ENV=production
      env_file:
      - .env
      ports:
        - $SERVER_PORT_EXPORT:$SERVER_PORT_EXPORT
      networks:
        - conectDB
      depends_on:
        - db
  db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - /data:/data/db
    networks:
      - conectDB
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
networks:
  conectDB:
    driver: bridge
volumes:
  mongodb_data:
